global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
      monitor: 'ci-monitoring'

rule_files: []

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor' 
    scrape_interval: 10s 
    static_configs:
{% for host in groups['all'] %} 
      - targets:
        - "{{ hostvars[host].ansible_host }}:{{ cadvisor_port }}"
        labels:
          host: "{{ host }}"
          
{% endfor %}

  - job_name: 'nodeexporter' 
    scrape_interval: 10s 
    static_configs:
{% for host in groups['all'] %} 
      - targets:
        - "{{ hostvars[host].ansible_host }}:{{ nodeexporter_port }}"
        labels:
          host: "{{ host }}"
{% endfor %}

